### ISSUE TITLE
Create documentation for demo environment configs

### ISSUE THREAD

**Issue by ieaves** [grai-io/grai-core#698]
Various docker deployment configs can be found in the [examples](https://github.com/grai-io/grai-core/tree/master/examples) folder alongside the cli command `grai demo start`. However these are largely undocumented. We should include more details in the various doc pages including

* a copy of the docker scripts
* A page about the cli demo commands

**Comment by Vasanthavel124** [comment]
can you assign me this?

**Comment by ieaves** [comment]
@Vasanthavel124 done!

**Comment by ieaves** [comment]
Hey @Vasanthavel124 just a quick checkin. Are you still working on this or should I unassign it?
