### ISSUE TITLE
[GRA-909] Add html to email for verification

### ISSUE THREAD

**Issue by edlouth** [grai-io/grai-core#702]
Current email template is at https://github.com/grai-io/grai-core/blob/af7a53ff85e0cd8b47698aca55f44897d9f583b6/grai-server/app/templates/auth/email_verification.txt but is text only, would be nice to add an html template.

I presume that Django has an off the shelf way to do this.

The current email could be improved with more text, sign off and so on.

<sub>[GRA-909](https://linear.app/grai/issue/GRA-909/add-html-to-email-for-verification)</sub>

**Comment by kunaldhand** [comment]
hey @edlouth, can I do this?

**Comment by edlouth** [comment]
@kunaldhand it is great to hear that you are interested in working on this issue. Please go head, you should now be assigned to the issue. If you need any pointers or help, please let me know.

**Comment by kunaldhand** [comment]
![email_template_example](https://github.com/grai-io/grai-core/assets/99679283/e5671206-651b-41e5-a83b-7cf2e1e2e542)
The Email Template I designed will look like this. Is this OK?

**Comment by kunaldhand** [comment]
> ![email_template_example](https://user-images.githubusercontent.com/99679283/274354042-e5671206-651b-41e5-a83b-7cf2e1e2e542.png) The Email Template I designed will look like this. Is this OK?

One more thing, do you want inline css or a different file of css>

**Comment by edlouth** [comment]
That looks great, inline css would probably be easiest.

**Comment by kunaldhand** [comment]
I have submitted a pull request kindly revise it and merge it @edlouth .

**Comment by kunaldhand** [comment]
Are we done here @edlouth ? You merged the proposed pull request, so I believe this issue is fixed now. One more thing, this project is also missing a password reset email template. If you want I can make that template too. You can open a new issue and assigned it to me, if you like.

**Comment by edlouth** [comment]
Yes this is all done, I have linked the PR and will close. I will open a new ticket for the password reset email, it would be great if you could take a look.

**Comment by kunaldhand** [comment]
> Yes this is all done, I have linked the PR and will close. I will open a new ticket for the password reset email, it would be great if you could take a look.

Sure, It would be great if you assign the new ticket of Password Verification Template to me, whenever you open it.
